version: '3'

services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - flask1
      - flask2

  flask1:
    build: 
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5001:5000"

  flask2:
    build: 
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5002:5000"

